### ISSUE TITLE
Analyzer does not read some thread messages 

### ISSUE THREAD

**Issue by Madoxen** [Madoxen/FacebookDataAnalyzer#1]
Some FBThreads are throwing exceptions when we try to fetch messages from them.

Current hypothesis is as follows:
- It's probably a problem with ThreadIDs, some people have custom id's and some use uid, those with uids are being read, those with custom not.

**Comment by Madoxen** [comment]
Update, my recent findings: It seems that the problem lies elsewhere, i've loaded entire FbChat C# lib into the solution, and it seems like some of messages cannot be parsed, because some delimiter is missing, below is a dump of one of exception throws: 

`Unterminated string. Expected delimiter: ". Path 'q0.data.message_thread.last_message.nodes[0].snippet', line 1, position 350.   at Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote)
FacebookDataAnalyzer>    at Newtonsoft.Json.JsonTextReader.ParseValue()
FacebookDataAnalyzer>    at Newtonsoft.Json.JsonTextReader.Read()
FacebookDataAnalyzer>    at Newtonsoft.Json.Linq.JContainer.ReadContentFrom(JsonReader r, JsonLoadSettings settings)
FacebookDataAnalyzer>    at Newtonsoft.Json.Linq.JContainer.ReadTokenFrom(JsonReader reader, JsonLoadSettings options)
FacebookDataAnalyzer>    at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
FacebookDataAnalyzer>    at Newtonsoft.Json.Linq.JToken.ReadFrom(JsonReader reader, JsonLoadSettings settings)
FacebookDataAnalyzer>    at Newtonsoft.Json.Linq.JToken.Parse(String json, JsonLoadSettings settings)
FacebookDataAnalyzer>    at Newtonsoft.Json.Linq.JToken.Parse(String json)
FacebookDataAnalyzer>    at fbchat_sharp.API.GraphQL_JSON_Decoder.graphql_response_to_json(String content) in D:\Projects\fbchat-sharp\fbchat-sharp\API\GraphQl.cs:line 311
FacebookDataAnalyzer>    at fbchat_sharp.API.Client._graphql(Dictionary`2 payload, Int32 error_retries) in D:\Projects\fbchat-sharp\fbchat-sharp\API\Client.cs:line 273
FacebookDataAnalyzer>    at fbchat_sharp.API.Client.graphql_requests(List`1 queries) in D:\Projects\fbchat-sharp\fbchat-sharp\API\Client.cs:line 376
FacebookDataAnalyzer>    at fbchat_sharp.API.Client.graphql_request(GraphQL query) in D:\Projects\fbchat-sharp\fbchat-sharp\API\Client.cs:line 387
FacebookDataAnalyzer>    at fbchat_sharp.API.Client.fetchThreadMessages(String thread_id, Int32 limit, String before) in D:\Projects\fbchat-sharp\fbchat-sharp\API\Client.cs:line 1215
FacebookDataAnalyzer>    at FacebookDataAnalyzer.Analyzer.FetchUserMessages(FB_User user) in D:\Projects\FacebookDataAnalyzer\Analyzer.cs:line 105
FacebookDataAnalyzer>    at FacebookDataAnalyzer.Analyzer.AnalyzeThread(FB_User user) in D:\Projects\FacebookDataAnalyzer\Analyzer.cs:line 72`

**Comment by Madoxen** [comment]
Solved with 133628f
